### ISSUE TITLE
Nice package! Exactly what I was looking for! Android/Kotlin?

### ISSUE THREAD

**Issue by CyonAlexRDX** [jrothwell/VersionedCodable#4]
Hey! This package seems like a good fit for ou teams iOS app, but we have the same challenge for Android (Kotlin), I saw you had [an unrelated Kotlin repo](https://github.com/jrothwell/santa-sorter), have you solved the Versioning for Android (Kotlin) as well? 

Thanks!

**Comment by jrothwell** [comment]
Hej @CyonAlexRDX, no I haven't. `VersionedCodable` is extracted from [Unspool](https://www.unspool.app), an app I am writing for the Mac. I do know Kotlin but I have no reason to write a Kotlin version of `VersionedCodable`.

In addition, I'm not sure it's really possible because, to my knowledge, Kotlin's standard library doesn't have a `Codable` equivalent ([kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) might fit the bill as something that isn't tied to **just** dealing with JSON.) It might be a fun problem to solve, but it's not on my radar. Sorry.
